### ISSUE TITLE
function Get-AdobeAuthToken Validation Issue

### ISSUE THREAD

**Issue by mharrison0224** [zincarla/AdobeUMInterface#1]
Current Line:
[ValidateScript({$_.Token -ne $null})] 

Should Be:

[ValidateScript({$_.Token -eq $null})]

Function errored out on me until i changed that line. Function's purpose is to change $ClientInformation.Token from a $null value to the token generated by function.

Also thank you for this code! You saved me hours upon hours of work. You rule.

**Comment by zincarla** [comment]
Jesus I need to watch my repos more often. No worries! Which line does it need to be changed in? Unfortunately my company didn't renew their license so I don't think I can really test this anymore :/

**Comment by zincarla** [comment]
Didn't realize you had added to title, my bad. Updated code. Let me know if you find anything else! I just removed the validation. Without a validator on that function, allows the user to request a new token if needed without creating a whole new client info object.
