### ISSUE TITLE
400 Bad Request on New-SyncADGroupRequest

### ISSUE THREAD

**Issue by Th1sD0t** [zincarla/AdobeUMInterface#13]
When trying to send a New-SyncADGroupRequest, I'm always receiving a Bad Request error.

**Comment by Th1sD0t** [comment]
```
$request = New-SyncADGroupRequest -ADGroupName $adGroup -AdobeGroupName $GroupAssociation[$adGroup] -ClientInformation $clientInformation
Send-UserManagementRequest -Requests $request -ClientInformation $clientInformation
```

**Comment by Th1sD0t** [comment]
Seems like this was caused by too many requests handed over to Send-UserManagementRequest. Limiting the amount of requests to 10 (or sending one by one) resolved the issue.

**Comment by zincarla** [comment]
Good to know, I knew adobe limited requests, but I thought they only limited the number of requests sent as separate requests, not necessarily blocking one big collection of requests. I'm re-opening issue as I would like to get this to work with any sized requests out-of-box.

**Comment by zincarla** [comment]
I was able to replicate this issue recently. Probable fix pushed to repo. Send-UserManagementRequest now automatically breaks requests up into chunks of 10. Also added a check for throttling response.
