### ISSUE TITLE
Typos in New-RemoveFromGroupRequest

### ISSUE THREAD

**Issue by timowilliams** [zincarla/AdobeUMInterface#20]
![2020-12-10_08h51_35](https://user-images.githubusercontent.com/6457359/101698682-a9ff9600-3ac5-11eb-813d-ba3d4d18b120.png)

**Comment by zincarla** [comment]
Thank you for the assistance. I just commited a fix for it, db6b189. The `New-RemoveFromGroupRequest` has been removed and added to `New-RemoveUserFromGroupRequest` as an alias. I realized going through this, that they are intended to do the same thing. The only difference is `New-RemoveUserFromGroupRequest` supports the domain parameter. With the aliases in place, both function names should work. Thanks again.
