### ISSUE TITLE
function Get-AdobeUsers broken

### ISSUE THREAD

**Issue by hosmancevic** [zincarla/AdobeUMInterface#3]
Hi,

The function Get-AdobeUsers seems to be broken since 2-3 weeks now.

**Comment by zincarla** [comment]
What happens when that function is called on your end? I tried it locally but it just pulled the list of our users :/

**Comment by hosmancevic** [comment]
We are getting this error since a couple of weeks, it was working for some months..
This is when using Get-AdobeGroups, not the users. I am sorry for the confusion.

`Invoke-RestMethod : The remote server returned an error: (400) Bad Request.
At C:\Scripts\AdobeUserSync\AdobeUMInterface.psm1:521 char:30
+ ... yResponse = Invoke-RestMethod -Method Get -Uri ($URIPrefix+$Page.ToSt ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand`

**Comment by zincarla** [comment]
I tested it on my side and ran into the same issue. It took me longer than I'd like to admit but I found the bug. I have no clue why this was not an issue earlier. The URL it was generating to grab groups ended up with a double slash in it. I removed the extra slash and it now works on my side. Grab the updated module and give it a shot.

**Comment by zincarla** [comment]
Any Luck?

**Comment by hosmancevic** [comment]
Hi,

This solved the issue, thank you!

**Comment by zincarla** [comment]
Woot
