### ISSUE TITLE
Use an already installed certificate instead of a PFX file

### ISSUE THREAD

**Issue by rosellim** [zincarla/AdobeUMInterface#4]
Thank you for all of your great work as it has saved me considerable time. I have a need to only use pre-installed certificates rather than exported and i noticed in your code about a comment that you were unable to get the private key using PS certificate provider, cert:\.

You can use the GetRSAPrivateKey method from System.Security.Cryptography.X509Certificates.RSACertificateExtensions to achieve this. I have tested the below code in my own project and it works. (hope the formatting comes out ok.)

```powershell
function Get-CertPrivateKey
{
	[cmdletbinding()]
	Param
	(
		[Parameter(Mandatory = $true,ValueFromPipeline = $true,ParameterSetName="ByObject")]
		[System.Security.Cryptography.X509Certificates.X509Certificate2]$Certificate,
		[Parameter(Mandatory = $true,ParameterSetName="ByCertHash")]
		[string]$thumbprint
	)
	
	if($PsCmdlet.ParameterSetName -eq "ByCertHash"){
		$Certificate = Get-ChildItem cert: -Recurse | where-object{ $_.Thumbprint -eq "$thumbprint" } | Select-Object -last 1
	}
	
	$rsaKey = [System.Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPrivateKey($certificate)
	return $rsaKey
}
```

Hope it helps.

**Comment by zincarla** [comment]
Thanks for the function! It does get the private key, however I think this would only work with certs using RSA and I am not sure how to sign data using it as it returns CngKey. **_However_** this did end up leading me to [this Microsoft documentation](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.x509certificates.x509certificate2?view=netframework-4.7.2) which has a complete example in C# on how to get certificates from the user or machine store with the private key as a `X509Certificate2` object. I tested it a bit already and I think the below function can be used as a drop in replacement for `Import-PFXCert`. I will test more fully tomorrow. If it does work, I will deprecate `Import-PFXCert` and start using this from now on.
```powershell
<#
.SYNOPSIS
    Load a certificate with a private key from either a file or from a certificate store
.PARAMETER Password
    Password to open PFX
.PARAMETER CertPath
    Path to PFX File
.PARAMETER CertSerial
    Serial number of the cert to load
.PARAMETER CertStore
    Which store to load cert from (LocalMachine or CurrentUser)
.NOTES
    If you hard-code the password in a script utilizing this function, you should ensure the script is itself, somewhere secure.
    The account running this function may need additional permissions to load private key from LocalMachine store.
.EXAMPLE
    Import-AdobeUMCert -Password "ASDF" -CertPath "C:\Cert.pfx"

.EXAMPLE
    Import-AdobeUMCert -CertSerial "00000000000000000000000000000000" -CertStore "LocalMachine"
#>
function Import-AdobeUMCert
{
    Param
    (
        [Parameter(Mandatory=$true,ParameterSetName='FromFile')][string]$Password,
        [ValidateScript({Test-Path -Path $_})]
        [Parameter(Mandatory=$true,ParameterSetName='FromFile')][string]$CertPath,
        [Parameter(Mandatory=$true,ParameterSetName='FromStore')][string]$CertSerial,
        [Parameter(ParameterSetName='FromStore')][ValidateSet('CurrentUser','LocalMachine')]$CertStore
    )
    if ($PSCmdlet.ParameterSetName -eq "FromStore") {
        #Convert cert store to the correct enum value
        if ($CertStore -eq "CurrentUser") {
            $CertStore = [System.Security.Cryptography.X509Certificates.StoreLocation]::CurrentUser
        } elseif ($CertStore -eq "LocalMachine") {
            $CertStore = [System.Security.Cryptography.X509Certificates.StoreLocation]::LocalMachine
        }
        #Open the certificate store
        $Store = New-Object -TypeName System.Security.Cryptography.X509Certificates.x509Store -ArgumentList @($CertStore)
        $Store.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadOnly)

        #Now search for certificate by thumbprint
        $Collection = $Store.Certificates.Find([System.Security.Cryptography.X509Certificates.X509FindType]::FindBySerialNumber, $CertSerial, $false)
        $Store.Dispose() #Make sure we cleanup after ourselves
    }
    elseif ($PSCmdlet.ParameterSetName -eq "FromFile")
    {
        #Load cert in by file
        $Collection = [System.Security.Cryptography.X509Certificates.X509Certificate2Collection]::new()
        $Collection.Import($CertPath, $Password, [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::PersistKeySet)
    }
    return $Collection[0]
}
```

**Comment by rosellim** [comment]
Looks good! Understand about RSA only and I didn’t even think of trying to connect using .NET, and I have C# code that I use for certificate installation checks for MSI builds. Going to give it a whirl in my code as well.

I used the cngKey the same way you used it 😊


$certificate = Get-ChildItem cert: -Recurse | where-object{ $_.Thumbprint -eq "$thumbprint" } | Select-Object -last 1

$rsaKey = [System.Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPrivateKey($certificate)

$JWT = ConvertTo-Base64URL -Item ($rsaKey.SignData([System.Text.ASCIIEncoding]::UTF8.GetBytes($JWT_Body), [System.Security.Cryptography.HashAlgorithmName]::SHA256, [System.Security.Cryptography.RSASignaturePadding]::Pkcs1))

**Comment by zincarla** [comment]
Oooh, I did not see the "SignData" function in the documentation. Gotcha.

**Comment by zincarla** [comment]
I think that should do it. The `Import-PFXCert` function has been deprecated. `Import-AdobeUMCert` is a more descriptive a name. The new funcation can still load from file if needed, but can also load from the Windows store. Tested locally and it works! **Way** better than having the cert as a file and the password embedded in script.

**Comment by rosellim** [comment]
Works great for me. Thanks!!! 

Happy coding
