### ISSUE TITLE
Create federated user issue

### ISSUE THREAD

**Issue by ChrFrohn** [zincarla/AdobeUMInterface#5]
Hey!
Thanks for the great powershell modul - Love the work!

I'm having some issues with creating a federated user.
I keep gettings this error:
errors              : {@{index=0; step=0; message=Domain field only allowed for non-email user names; errorCode=error.command.domain.must_be_used_with_nonemail_username}}

The reques is like this: $Request = New-CreateUserRequest -FirstName "John" -LastName "Doe" -Email "John.Doe@domain.com" -IDType federated -Domain domain.com

I have tried mulitple combations but i keep ending up with that error or another error.

Can you tell me if there is a bug? or I'm i doing it wrong? - I could not find an example on how to create a fredated user, even though a read the entire function in the modul.
Can you prove me with an example on how to create a federated user?

**Comment by zincarla** [comment]
Thank you for the feedback. We do not use federated authentication yet so I cannot test it myself. I *think* I have an idea on what the issue is though. I created a new branch with the hopeful fix. The error you got back complains about the username being the email address. In the new branch, I added a new parameter so you can specifiy the username, normally the script just uses whatever you enter for e-mail. The new function should be used like:
```powershell
$Request = New-CreateUserRequest -FirstName "John" -LastName "Doe" -UserID "John.Doe" -Email "John.Doe@domain.com" -IDType federated -Domain domain.com
```
I am not 100% sure how the UserID should be formatted. I am guessing it should match the username that your federation service is expecting. 

Do you mind giving it a shot? Updated branch is [AttemptFederationFix](https://github.com/zincarla/AdobeUMInterface/tree/AttemptFederationFix). If you verify it works, I will merge it into the master branch.

**Comment by ChrFrohn** [comment]
Hi Zincarla

Thanks for getting back to me and looking in to the issue.

Im now gettings this error:
errors: {@{index=0; step=0; message=Domain field only allowed for non-email user names; errorCode=error.command.domain.must_be_used_with_nonemail_username}}

The user info for a federated user at my end looks like this:
email     : jd@domain.com
status    : active
groups    : "Some group name"
username  : jd@domain.com
domain    : domain.com
firstname : John
lastname  : Doe
country   : DK
type      : federatedID

**Comment by zincarla** [comment]
Good Morning Lilwackz, 
I assumed the domain field would be ignored if not needed, like the enterprise method does per the [Adobe API](https://adobe-apiplatform.github.io/umapi-documentation/en/api/ActionsCmds.html#createFederatedID), but guess not. I updated the [AttemptFederationFix branch](https://github.com/zincarla/AdobeUMInterface/tree/AttemptFederationFix) and made the domain portion optional. Could you try it again but without the domain parameter?

```powershell
$Request = New-CreateUserRequest -FirstName "John" -LastName "Doe" -UserID "jd@domain.com" -Email "jd@domain.com" -IDType federated -Country DK
```

**Comment by ChrFrohn** [comment]
Hey Zincarla
Sorry for det delayed response, thank you once again for taking the time to look in to the bug.

Unfortunately it did not resolve the issue, but I may have a work around, I will share it tomorrow

**Comment by ChrFrohn** [comment]
I was able to resolve the issue with a C/P from Paul Towler (se code below) so i basically to replace the code in your function with his. (I was kinda desperate), so all credit to him for this solution.  
https://www.powershellgallery.com/packages/AdobeUM.AzureAD/1.0.1/Content/AdobeUM.AzureAD.psm1

```powershell
function New-CreateUserRequest
{
    Param
    (
        [Parameter(Mandatory=$true)]
        [string]$FirstName,

        [Parameter(Mandatory=$true)]
        [string]$LastName, 

        [Parameter(Mandatory=$true)]
        [string]$Email, 

        [string]$Country="AU", 

        $AdditionalActions=@()
    )

    # Parameters to create a new federatedID
    $FederatedIDParameters = New-Object -TypeName PSObject -Property @{email=$Email;country=$Country;firstname=$FirstName;lastname=$LastName}

    # Federated ID creation action
    $FederatedIDAction = New-Object -TypeName PSObject -Property @{createFederatedID=$FederatedIDParameters}

    # Add any additional actions
    $AdditionalActions = @()+ $FederatedIDAction + $AdditionalActions

    # Return the new request
    return (New-Object -TypeName PSObject -Property @{user=$Email;do=@()+$AdditionalActions})


}
```

**Comment by zincarla** [comment]
Thank you for the example script. I compared the outputs and found a bug in mine. Even when no domain was specified, since I had `[string]$Domain` as the parameter, powershell helpfully converted it from `$null` to `""`. So the request was sending Adobe a blank domain name with each request.
