### ISSUE TITLE
Unable to read Private Key

### ISSUE THREAD

**Issue by StAloysius** [zincarla/AdobeUMInterface#9]
Hi,

I am running your script and so far all good.
But, when I try to run the `Get-AdobeAuthToken -ClientInformation $ClientInformation -SignatureCert $SignatureCert` it gives an error about the Private Key being Null.
I know the cert has a private key as I can see in windows it says it does.

Any thoughts on what might be going on??

Cheers

**Comment by StAloysius** [comment]
OK, so I got to the bottom of this one.
Apprarently on Windows Server 2012R2 and below there is no way to create a cert with `-Provider "Microsoft Enhanced RSA and AES Cryptographic Provider"` so I had hacked your command to make my own.
This has flow-on effect of creating a cert with KSP and .NET / Powershell cannot read these.

So, I tried to create the cert from Windows 10 and voila it works!!!

Thanks for the great tool, it is going to save my day... no manual account creation 👍

**Comment by dfranciscus** [comment]
@StAloysius so there is no workaround on Server 2012 R2?

**Comment by zincarla** [comment]
Reopening issue to create a native fix for this

**Comment by zincarla** [comment]
Added warning to the new cert function in meantime. Have not found a viable option so far in powershell.

**Comment by StAloysius** [comment]
I found the following PS Module that will generate the correct certificate
https://github.com/PKISolutions/PSPKI
Tested locally and it creates a certificate with `Microsoft Enhanced RSA and AES Cryptographic Provider` as the provider.
Not sure how to best integrate it though.

**Comment by zincarla** [comment]
Since this relates to Server 2012, I think I will mark this as wontfix. 2012 is out the door, workaround for anyone with this issue and 2012 should be to generate a cert using another tool and import with the correct CSP.
